### PR TITLE
Split SimpleRDF into SimpleRDF (store code) and SimpleRDF-Lite (none store code)

### PR DESCRIPTION
**Pull request by bergos**
This patch splits the package into two packages. The new SimpleRDF-Lite package doesn't require the rdf-store-ldp package and all of it's nested dependencies. The functionality of the SimpleRDF package stays the same.

This requires a new dependency! [simplerdf-lite](https://github.com/bergos/simplerdf-lite)

### CODE REVIEW

**Comment by nicola** [comment]
This is such of a huge change that basically take away all the functionality into `simplerdf-lite`.

I am not sure this is a good idea. I was thinking of something on these lines: `require('simplerdf')` to have the "light" version and `require('simplerdf/full')` or similar. In this way it is still the same package.

I would like to avoid dependencies with the library itself

**Comment by bergos** [comment]
The library has already a big dependency and that's the `rdf-store-ldp`. That's the main reason for me to split the library. Your proposal doesn't fix that problem. And by default `simplerdf` should be the full library.

btw. I created the `simplerdf-lite` package with your github namespace because it contains mainly your code/ideas and you should have control over it.

**Comment by csarven** [comment]
As a user, I can only +1 the initiative to have a lite version available. Also, wasn't there an initiative to browserify a version by more or less ticking some boxes for the libraries?

**Comment by nicola** [comment]
@bergos tell me how to proceed on this, is the package on.. NPM?

**Comment by nicola** [comment]
@bergos:
- publish lite
- merge it
- publish simplerdf

**Pull request closed without merging**
